server:
  port: 8001
  #mybatis配置
mybatis:
  type-aliases-package: com.kuang.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # spring配置
spring:
    application:
      name: dept-provider
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sqlTest?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
